name: bible_quiz
description: Multilingual Bible Quiz App - Kahoot Style
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  firebase_auth: ^5.5.1
  provider: ^6.1.2
  confetti: ^0.8.0
  cupertino_icons: ^1.0.8
  image_picker: ^1.2.2
  firebase_storage: ^12.4.10
  share_plus: ^10.0.0
  shared_preferences: ^2.3.2
  path_provider: ^2.1.0
  flutter_tts: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/real_questions.json
    - assets/bible/
  fonts:
    - family: NotoSansTelugu
      fonts:
        - asset: assets/fonts/NotoSansTelugu-Regular.ttf
        - asset: assets/fonts/NotoSansTelugu-Bold.ttf
          weight: 700
    - family: NotoSansDevanagari
      fonts:
        - asset: assets/fonts/NotoSansDevanagari-Regular.ttf
        - asset: assets/fonts/NotoSansDevanagari-Bold.ttf
          weight: 700
    - family: NotoSansTamil
      fonts:
        - asset: assets/fonts/NotoSansTamil-Regular.ttf
        - asset: assets/fonts/NotoSansTamil-Bold.ttf
          weight: 700
    - family: NotoSansMalayalam
      fonts:
        - asset: assets/fonts/NotoSansMalayalam-Regular.ttf
        - asset: assets/fonts/NotoSansMalayalam-Bold.ttf
          weight: 700
    - family: NotoSansKannada
      fonts:
        - asset: assets/fonts/NotoSansKannada-Regular.ttf
        - asset: assets/fonts/NotoSansKannada-Bold.ttf
          weight: 700
    - family: NotoSerif
      fonts:
        - asset: assets/fonts/NotoSerif-Regular.ttf
        - asset: assets/fonts/NotoSerif-Bold.ttf
          weight: 700
    - family: NotoSerifTelugu
      fonts:
        - asset: assets/fonts/NotoSerifTelugu-Regular.ttf
        - asset: assets/fonts/NotoSerifTelugu-Bold.ttf
          weight: 700
