class ChallengeQuestions {
  static List<Map<String, dynamic>> getDailyQuestions() {
    return [
      {
        'id': 'daily_q1',
        'order': 1,
        'type': 'multiple_choice',
        'timeLimitSeconds': 45,
        'points': 100,
        'questionEn': 'On which day did God create light?',
        'questionTe': 'దేవుడు ఏ రోజున వెలుగును సృష్టించాడు?',
        'options': [
          {'id': 'o1', 'order': 1, 'isCorrect': true, 'textEn': 'Day 1', 'textTe': 'మొదటి రోజు'},
          {'id': 'o2', 'order': 2, 'isCorrect': false, 'textEn': 'Day 2', 'textTe': 'రెండవ రోజు'},
          {'id': 'o3', 'order': 3, 'isCorrect': false, 'textEn': 'Day 3', 'textTe': 'మూడవ రోజు'},
          {'id': 'o4', 'order': 4, 'isCorrect': false, 'textEn': 'Day 4', 'textTe': 'నాల్గవ రోజు'},
        ],
        'correctAnswerEn': 'Day 1',
        'correctAnswerTe': 'మొదటి రోజు',
        'verseReferenceEn': 'Genesis 1:3-5',
        'verseReferenceTe': 'ఆదికాండము 1:3-5',
        'explanationEn': 'God said, "Let there be light," and there was light on the first day.',
        'explanationTe': 'దేవుడు "వెలుగు కలుగును గాక" అని పలికెను, అప్పుడు మొదటి రోజున వెలుగు కలిగెను.'
      },
      {
        'id': 'daily_q2',
        'order': 2,
        'type': 'multiple_choice',
        'timeLimitSeconds': 45,
        'points': 100,
        'questionEn': 'What did God do on the seventh day?',
        'questionTe': 'దేవుడు ఏడవ రోజున ఏమి చేశాడు?',
        'options': [
          {'id': 'o1', 'order': 1, 'isCorrect': true, 'textEn': 'Rested from all His work', 'textTe': 'తన సృష్టి కార్యములన్నిటి నుండి విశ్రమించెను'},
          {'id': 'o2', 'order': 2, 'isCorrect': false, 'textEn': 'Created mankind', 'textTe': 'నరులను సృష్టించెను'},
          {'id': 'o3', 'order': 3, 'isCorrect': false, 'textEn': 'Formed the dry land', 'textTe': 'ఆరిన నేలను కలుగజేసెను'},
          {'id': 'o4', 'order': 4, 'isCorrect': false, 'textEn': 'Created stars', 'textTe': 'నక్షత్రాలను సృష్టించెను'},
        ],
        'correctAnswerEn': 'Rested from all His work',
        'correctAnswerTe': 'తన సృష్టి కార్యములన్నిటి నుండి విశ్రమించెను',
        'verseReferenceEn': 'Genesis 2:2-3',
        'verseReferenceTe': 'ఆదికాండము 2:2-3',
        'explanationEn': 'God blessed the seventh day and sanctified it because on it He rested from all His work.',
        'explanationTe': 'దేవుడు ఏడవ దినమును ఆశీర్వదించి పరిశుద్ధపరిచెను, ఏలయనగా ఆ దినమున ఆయన తన సృష్టి కార్యములన్నిటి నుండి విశ్రమించెను.'
      },
      {
        'id': 'daily_q3',
        'order': 3,
        'type': 'multiple_choice',
        'timeLimitSeconds': 45,
        'points': 100,
        'questionEn': 'In whose image did God create mankind?',
        'questionTe': 'దేవుడు నరుడిని ఎవరి పోలిక చొప్పున సృష్టించాడు?',
        'options': [
          {'id': 'o1', 'order': 1, 'isCorrect': true, 'textEn': 'In His own image', 'textTe': 'తన స్వంత స్వరూపమందు'},
          {'id': 'o2', 'order': 2, 'isCorrect': false, 'textEn': 'In the image of angels', 'textTe': 'దేవదూతల పోలిక చొప్పున'},
          {'id': 'o3', 'order': 3, 'isCorrect': false, 'textEn': 'In the image of stars', 'textTe': 'నక్షత్రాల పోలిక చొప్పున'},
          {'id': 'o4', 'order': 4, 'isCorrect': false, 'textEn': 'In the image of other creatures', 'textTe': 'ఇతర ప్రాణుల పోలిక చొప్పున'},
        ],
        'correctAnswerEn': 'In His own image',
        'correctAnswerTe': 'తన స్వంత స్వరూపమందు',
        'verseReferenceEn': 'Genesis 1:27',
        'verseReferenceTe': 'ఆదికాండము 1:27',
        'explanationEn': 'God created man in His own image, in the image of God He created them; male and female He created them.',
        'explanationTe': 'దేవుడు తన స్వరూపమందు నరుని సృష్టించెను; దేవుని స్వరూపమందు వాని సృష్టించెను; స్త్రీనిగాను పురుషునిగాను వారిని సృష్టించెను.'
      },
      {
        'id': 'daily_q4',
        'order': 4,
        'type': 'multiple_choice',
        'timeLimitSeconds': 45,
        'points': 100,
        'questionEn': 'Who built an ark to save his family from the flood?',
        'questionTe': 'జలప్రళయం నుండి తన కుటుంబాన్ని రక్షించడానికి ఓడను నిర్మించింది ఎవరు?',
        'options': [
          {'id': 'o1', 'order': 1, 'isCorrect': true, 'textEn': 'Noah', 'textTe': 'నోవహు'},
          {'id': 'o2', 'order': 2, 'isCorrect': false, 'textEn': 'Abraham', 'textTe': 'అబ్రాహాము'},
          {'id': 'o3', 'order': 3, 'isCorrect': false, 'textEn': 'Moses', 'textTe': 'మోషే'},
          {'id': 'o4', 'order': 4, 'isCorrect': false, 'textEn': 'Jacob', 'textTe': 'యాకోబు'},
        ],
        'correctAnswerEn': 'Noah',
        'correctAnswerTe': 'నోవహు',
        'verseReferenceEn': 'Genesis 6:13-22',
        'verseReferenceTe': 'ఆదికాండము 6:13-22',
        'explanationEn': 'Noah built the ark exactly as God commanded him, saving his family and pairs of every animal.',
        'explanationTe': 'దేవుడు ఆజ్ఞాపించినట్లు నోవహు ఓడను నిర్మించి, తన కుటుంబాన్ని మరియు జంతువులను రక్షించెను.'
      },
      {
        'id': 'daily_q5',
        'order': 5,
        'type': 'type_answer',
        'timeLimitSeconds': 90,
        'points': 100,
        'questionEn': 'Fill in the blank: "The Lord is my shepherd; I shall not _______."',
        'questionTe': 'ఖాళీని పూరించండి: "యెహోవా నా కాపరి; నాకు _______ కలుగదు."',
        'options': [],
        'correctAnswerEn': 'want',
        'correctAnswerTe': 'లేమి',
        'verseReferenceEn': 'Psalm 23:1',
        'verseReferenceTe': 'కీర్తన 23:1',
        'explanationEn': 'David declares that because God is his loving shepherd, he will lack nothing.',
        'explanationTe': 'దేవుడు తన కాపరియై ఉన్నందున తనకు ఏ లోటు కలుగదని దావీదు ప్రకటించాడు.'
      },
      {
        'id': 'daily_q6',
        'order': 6,
        'type': 'multiple_choice',
        'timeLimitSeconds': 45,
        'points': 100,
        'questionEn': 'Where was Jesus born?',
        'questionTe': 'యేసు ఎక్కడ జన్మించాడు?',
        'options': [
          {'id': 'o1', 'order': 1, 'isCorrect': true, 'textEn': 'Bethlehem', 'textTe': 'బెత్లేహేము'},
          {'id': 'o2', 'order': 2, 'isCorrect': false, 'textEn': 'Nazareth', 'textTe': 'నజరేతు'},
          {'id': 'o3', 'order': 3, 'isCorrect': false, 'textEn': 'Jerusalem', 'textTe': 'యెరూషలేము'},
          {'id': 'o4', 'order': 4, 'isCorrect': false, 'textEn': 'Rome', 'textTe': 'రోము'},
        ],
        'correctAnswerEn': 'Bethlehem',
        'correctAnswerTe': 'బెత్లేహేము',
        'verseReferenceEn': 'Matthew 2:1',
        'verseReferenceTe': 'మత్తయి 2:1',
        'explanationEn': 'Jesus was born in Bethlehem of Judea in the days of Herod the king.',
        'explanationTe': 'రాజైన హేరోదు దినములలో యూదయ దేశపు బెత్లేహేములో యేసు జన్మించెను.'
      },
      {
        'id': 'daily_q7',
        'order': 7,
        'type': 'true_false',
        'timeLimitSeconds': 45,
        'points': 100,
        'questionEn': 'True or False: Moses entered the Promised Land.',
        'questionTe': 'నిజమా లేక తప్పా: మోషే వాగ్దాన దేశంలో ప్రవేశించాడు.',
        'options': [],
        'correctAnswerEn': 'False',
        'correctAnswerTe': 'తప్పు',
        'verseReferenceEn': 'Deuteronomy 34:4',
        'verseReferenceTe': 'ద్వితీయోపదేశకాండము 34:4',
        'explanationEn': 'Moses saw the Promised Land from Mount Nebo but was not allowed to enter it.',
        'explanationTe': 'మోషే నెబో కొండపై నుండి వాగ్దాన దేశమును చూచెను కానీ అందులో ప్రవేశించుటకు అనుమతి పొందలేదు.'
      },
      {
        'id': 'daily_q8',
        'order': 8,
        'type': 'multiple_choice',
        'timeLimitSeconds': 45,
        'points': 100,
        'questionEn': 'Who baptized Jesus?',
        'questionTe': 'యేసునకు బాప్తిస్మమిచ్చినది ఎవరు?',
        'options': [
          {'id': 'o1', 'order': 1, 'isCorrect': true, 'textEn': 'John the Baptist', 'textTe': 'బాప్తిస్మమిచ్చు యోహాను'},
          {'id': 'o2', 'order': 2, 'isCorrect': false, 'textEn': 'Peter', 'textTe': 'పేతురు'},
          {'id': 'o3', 'order': 3, 'isCorrect': false, 'textEn': 'James', 'textTe': 'యాకోబు'},
          {'id': 'o4', 'order': 4, 'isCorrect': false, 'textEn': 'Paul', 'textTe': 'పౌలు'},
        ],
        'correctAnswerEn': 'John the Baptist',
        'correctAnswerTe': 'బాప్తిస్మమిచ్చు యోహాను',
        'verseReferenceEn': 'Matthew 3:13-17',
        'verseReferenceTe': 'మత్తయి 3:13-17',
        'explanationEn': 'Jesus came from Galilee to John at the Jordan to be baptized by him.',
        'explanationTe': 'యోహాను చేత బాప్తిస్మము పొందుటకు యేసు గలిలయ నుండి యొర్దాను దగ్గరకు వచ్చెను.'
      },
      {
        'id': 'daily_q9',
        'order': 9,
        'type': 'multiple_choice',
        'timeLimitSeconds': 45,
        'points': 100,
        'questionEn': 'What is the first book of the New Testament?',
        'questionTe': 'నూతన నిబంధనలో మొదటి గ్రంథము ఏది?',
        'options': [
          {'id': 'o1', 'order': 1, 'isCorrect': true, 'textEn': 'Gospel of Matthew', 'textTe': 'మత్తయి సువార్త'},
          {'id': 'o2', 'order': 2, 'isCorrect': false, 'textEn': 'Gospel of Mark', 'textTe': 'మార్కు సువార్త'},
          {'id': 'o3', 'order': 3, 'isCorrect': false, 'textEn': 'Gospel of Luke', 'textTe': 'లూకా సువార్త'},
          {'id': 'o4', 'order': 4, 'isCorrect': false, 'textEn': 'Gospel of John', 'textTe': 'యోహాను సువార్త'},
        ],
        'correctAnswerEn': 'Gospel of Matthew',
        'correctAnswerTe': 'మత్తయి సువార్త',
        'verseReferenceEn': 'Matthew 1:1',
        'verseReferenceTe': 'మత్తయి 1:1',
        'explanationEn': 'The New Testament starts with the Gospel of Matthew, documenting the genealogy of Jesus.',
        'explanationTe': 'నూతన నిబంధన యేసు వంశావళిని వివరించే మత్తయి సువార్తతో ప్రారంభమౌతుంది.'
      },
      {
        'id': 'daily_q10',
        'order': 10,
        'type': 'type_answer',
        'timeLimitSeconds': 90,
        'points': 100,
        'questionEn': 'Fill in the blank: "For God so loved the _______ that He gave His only Son."',
        'questionTe': 'ఖాళీని పూరించండి: "దేవుడు _______ ఎంతో ప్రేమించెను; ఆయన తన అద్వితీయ కుమారుని ఇచ్చెను."',
        'options': [],
        'correctAnswerEn': 'world',
        'correctAnswerTe': 'లోకమును',
        'verseReferenceEn': 'John 3:16',
        'verseReferenceTe': 'యోహాను 3:16',
        'explanationEn': 'John 3:16 outlines God\'s supreme love for the world, giving His Son so that whoever believes will not perish.',
        'explanationTe': 'లోకమును ప్రేమించి తన కుమారుని విశ్వసించు ప్రతివాడు నశింపక నిత్యజీవము పొందునట్లు ఆయనను అనుగ్రహించెను.'
      },
      {
        'id': 'daily_q11',
        'order': 11,
        'type': 'true_false',
        'timeLimitSeconds': 45,
        'points': 100,
        'questionEn': 'True or False: David wrote all 150 Psalms.',
        'questionTe': 'నిజమా లేక తప్పా: దావీదు కీర్తనల గ్రంథంలోని 150 కీర్తనలనూ రాశాడు.',
        'options': [],
        'correctAnswerEn': 'False',
        'correctAnswerTe': 'తప్పు',
        'verseReferenceEn': 'Psalms (Authorship)',
        'verseReferenceTe': 'కీర్తనలు (రచయితలు)',
        'explanationEn': 'While David wrote about 73 psalms, others were written by Asaph, the sons of Korah, Solomon, Moses, etc.',
        'explanationTe': 'దావీదు దాదాపు 73 కీర్తనలు వ్రాసినప్పటికీ, మిగిలిన వాటిని ఆసాపు, కోరహు కుమారులు, సొలొమోను, మోషే మొదలైనవారు వ్రాశారు.'
      },
      {
        'id': 'daily_q12',
        'order': 12,
        'type': 'type_answer',
        'timeLimitSeconds': 90,
        'points': 100,
        'questionEn': 'Name the first book of the Bible.',
        'questionTe': 'బైబిల్లోని మొదటి గ్రంథము పేరు చెప్పండి.',
        'options': [],
        'correctAnswerEn': 'Genesis',
        'correctAnswerTe': 'ఆదికాండము',
        'verseReferenceEn': 'Genesis 1:1',
        'verseReferenceTe': 'ఆదికాండము 1:1',
        'explanationEn': 'Genesis is the first book of the Pentateuch, detailing creation and early covenant history.',
        'explanationTe': 'ఆదికాండము పంచగ్రంథాలలో మొదటిది, ఇది సృష్టి మరియు ప్రారంభ నిబంధనల చరిత్రను వివరిస్తుంది.'
      }
    ];
  }

  static List<Map<String, dynamic>> getWeeklyQuestions() {
    return [
      // 1-6: Multiple Choice
      {
        'id': 'weekly_q1',
        'order': 1,
        'type': 'multiple_choice',
        'timeLimitSeconds': 45,
        'points': 100,
        'questionEn': 'Who was the first high priest of Israel?',
        'questionTe': 'ఇశ్రాయేలీయుల మొట్టమొదటి ప్రధాన యాజకుడు ఎవరు?',
        'options': [
          {'id': 'o1', 'order': 1, 'isCorrect': true, 'textEn': 'Aaron', 'textTe': 'అహరోను'},
          {'id': 'o2', 'order': 2, 'isCorrect': false, 'textEn': 'Moses', 'textTe': 'మోషే'},
          {'id': 'o3', 'order': 3, 'isCorrect': false, 'textEn': 'Eleazar', 'textTe': 'ఎల్యాజరు'},
          {'id': 'o4', 'order': 4, 'isCorrect': false, 'textEn': 'Joshua', 'textTe': 'యెహోషువ'},
        ],
        'correctAnswerEn': 'Aaron',
        'correctAnswerTe': 'అహరోను',
        'verseReferenceEn': 'Exodus 28:1',
        'verseReferenceTe': 'నిర్గమకాండము 28:1',
        'explanationEn': 'God chose Aaron, Moses\' brother, to serve as the first High Priest of Israel.',
        'explanationTe': 'యాజకత్వము జరిగించుటకై ఇశ్రాయేలీయుల మొదటి ప్రధాన యాజకునిగా మోషే సహోదరుడైన అహరోనును దేవుడు నియమించెను.'
      },
      {
        'id': 'weekly_q2',
        'order': 2,
        'type': 'multiple_choice',
        'timeLimitSeconds': 45,
        'points': 100,
        'questionEn': 'How many people were saved on Noah\'s ark during the flood?',
        'questionTe': 'జలప్రళయం సమయంలో నోవహు ఓడలో ఎంతమంది ప్రాణాలు రక్షించబడ్డాయి?',
        'options': [
          {'id': 'o1', 'order': 1, 'isCorrect': true, 'textEn': '8', 'textTe': '8 మంది'},
          {'id': 'o2', 'order': 2, 'isCorrect': false, 'textEn': '4', 'textTe': '4 గురు'},
          {'id': 'o3', 'order': 3, 'isCorrect': false, 'textEn': '10', 'textTe': '10 మంది'},
          {'id': 'o4', 'order': 4, 'isCorrect': false, 'textEn': '6', 'textTe': '6 గురు'},
        ],
        'correctAnswerEn': '8',
        'correctAnswerTe': '8 మంది',
        'verseReferenceEn': '1 Peter 3:20',
        'verseReferenceTe': '1 పేతురు 3:20',
        'explanationEn': 'Only eight people (Noah, his wife, his three sons, and their wives) survived on the ark.',
        'explanationTe': 'నోవహు, అతని భార్య, ముగ్గురు కుమారులు మరియు కోడళ్ళు మాత్రమే (మొత్తం ఎనిమిది మంది) ఓడలో రక్షించబడ్డారు.'
      },
      {
        'id': 'weekly_q3',
        'order': 3,
        'type': 'multiple_choice',
        'timeLimitSeconds': 45,
        'points': 100,
        'questionEn': 'Which prophet was swallowed by a great fish when running away from God?',
        'questionTe': 'దేవుని మాట వినక పారిపోతుండగా పెద్ద చేప చేత మింగబడిన ప్రవక్త ఎవరు?',
        'options': [
          {'id': 'o1', 'order': 1, 'isCorrect': true, 'textEn': 'Jonah', 'textTe': 'యోనా'},
          {'id': 'o2', 'order': 2, 'isCorrect': false, 'textEn': 'Elijah', 'textTe': 'ఏలీయా'},
          {'id': 'o3', 'order': 3, 'isCorrect': false, 'textEn': 'Daniel', 'textTe': 'దానియేలు'},
          {'id': 'o4', 'order': 4, 'isCorrect': false, 'textEn': 'Jeremiah', 'textTe': 'యిర్మీయా'},
        ],
        'correctAnswerEn': 'Jonah',
        'correctAnswerTe': 'యోనా',
        'verseReferenceEn': 'Jonah 1:17',
        'verseReferenceTe': 'యోనా 1:17',
        'explanationEn': 'Jonah was swallowed by a great fish and stayed in its belly for three days and nights.',
        'explanationTe': 'దేవుడు నియమించిన పెద్ద చేప యోనాను మింగెను; మూడు పగళ్ళు మూడు రాత్రులు యోనా ఆ చేప కడుపులో ఉండెను.'
      },
      {
        'id': 'weekly_q4',
        'order': 4,
        'type': 'multiple_choice',
        'timeLimitSeconds': 45,
        'points': 100,
        'questionEn': 'Where were believers first called "Christians"?',
        'questionTe': 'విశ్వాసులను మొట్టమొదట ఎక్కడ "క్రైస్తవులు" అని పిలిచారు?',
        'options': [
          {'id': 'o1', 'order': 1, 'isCorrect': true, 'textEn': 'Antioch', 'textTe': 'అంతియొకయ'},
          {'id': 'o2', 'order': 2, 'isCorrect': false, 'textEn': 'Jerusalem', 'textTe': 'యెరూషలేము'},
          {'id': 'o3', 'order': 3, 'isCorrect': false, 'textEn': 'Rome', 'textTe': 'రోము'},
          {'id': 'o4', 'order': 4, 'isCorrect': false, 'textEn': 'Ephesus', 'textTe': 'ఎఫెసు'},
        ],
        'correctAnswerEn': 'Antioch',
        'correctAnswerTe': 'అంతియొకయ',
        'verseReferenceEn': 'Acts 11:26',
        'verseReferenceTe': 'అపొస్తలుల కార్యములు 11:26',
        'explanationEn': 'The disciples were called Christians first in Antioch, where Barnabas and Saul taught many people.',
        'explanationTe': 'అంతియొకయలో మొట్టమొదట శిష్యులు క్రైస్తవులని పిలువబడిరి.'
      },
      {
        'id': 'weekly_q5',
        'order': 5,
        'type': 'multiple_choice',
        'timeLimitSeconds': 45,
        'points': 100,
        'questionEn': 'Which of the following is the longest chapter in the entire Bible?',
        'questionTe': 'బైబిలు మొత్తంలో అతి పెద్ద అధ్యాయం ఏది?',
        'options': [
          {'id': 'o1', 'order': 1, 'isCorrect': true, 'textEn': 'Psalm 119', 'textTe': 'కీర్తన 119'},
          {'id': 'o2', 'order': 2, 'isCorrect': false, 'textEn': 'Psalm 23', 'textTe': 'కీర్తన 23'},
          {'id': 'o3', 'order': 3, 'isCorrect': false, 'textEn': 'Isaiah 53', 'textTe': 'యెషయా 53'},
          {'id': 'o4', 'order': 4, 'isCorrect': false, 'textEn': 'Genesis 1', 'textTe': 'ఆదికాండము 1'},
        ],
        'correctAnswerEn': 'Psalm 119',
        'correctAnswerTe': 'కీర్తన 119',
        'verseReferenceEn': 'Psalm 119',
        'verseReferenceTe': 'కీర్తన 119',
        'explanationEn': 'Psalm 119 is the longest chapter in the Bible with 176 verses, focused on the beauty of God\'s Word.',
        'explanationTe': 'కీర్తనల గ్రంథములోని 119వ కీర్తన 176 వచనములతో బైబిలు మొత్తంలోనే అతి పెద్ద అధ్యాయముగా ఉంది.'
      },
      {
        'id': 'weekly_q6',
        'order': 6,
        'type': 'multiple_choice',
        'timeLimitSeconds': 45,
        'points': 100,
        'questionEn': 'Who was known as the interpreter of dreams in Egypt?',
        'questionTe': 'ఐగుప్తు దేశంలో కలలకు భావము చెప్పినవాడిగా ప్రసిద్ధి పొందింది ఎవరు?',
        'options': [
          {'id': 'o1', 'order': 1, 'isCorrect': true, 'textEn': 'Joseph', 'textTe': 'యోసేపు'},
          {'id': 'o2', 'order': 2, 'isCorrect': false, 'textEn': 'Daniel', 'textTe': 'దానియేలు'},
          {'id': 'o3', 'order': 3, 'isCorrect': false, 'textEn': 'Moses', 'textTe': 'మోషే'},
          {'id': 'o4', 'order': 4, 'isCorrect': false, 'textEn': 'Aaron', 'textTe': 'అహరోను'},
        ],
        'correctAnswerEn': 'Joseph',
        'correctAnswerTe': 'యోసేపు',
        'verseReferenceEn': 'Genesis 41:15-16',
        'verseReferenceTe': 'ఆదికాండము 41:15-16',
        'explanationEn': 'Joseph interpreted Pharaoh\'s dreams of seven fat and thin cows, credit and praise going to God.',
        'explanationTe': 'ఫరో కలల భావమును దేవుని సహాయముతో యోసేపు వివరించి ఐగుప్తుకు అధికారియై నిలిచెను.'
      },

      // 7-11: True/False
      {
        'id': 'weekly_q7',
        'order': 7,
        'type': 'true_false',
        'timeLimitSeconds': 45,
        'points': 100,
        'questionEn': 'True or False: Sarah was 90 years old when Isaac was born.',
        'questionTe': 'నిజమా లేక తప్పా: ఇస్సాకు జన్మించినప్పుడు శారమ్మ వయస్సు 90 సంవత్సరాలు.',
        'options': [],
        'correctAnswerEn': 'True',
        'correctAnswerTe': 'నిజం',
        'verseReferenceEn': 'Genesis 17:17',
        'verseReferenceTe': 'ఆదికాండము 17:17',
        'explanationEn': 'God promised Abraham that Sarah, aged 90, would bear a son, which was fulfilled in Isaac.',
        'explanationTe': 'తొంబది ఏండ్ల శారమ్మకు కుమారుడు పుట్టునని దేవుడు వాగ్దానము చేసెను, అది ఇస్సాకు జననముతో నెరవేరెను.'
      },
      {
        'id': 'weekly_q8',
        'order': 8,
        'type': 'true_false',
        'timeLimitSeconds': 45,
        'points': 100,
        'questionEn': 'True or False: The Apostle Paul was originally named Saul.',
        'questionTe': 'నిజమా లేక తప్పా: అపొస్తలుడైన పౌలు అసలు పేరు మొదట సౌలు.',
        'options': [],
        'correctAnswerEn': 'True',
        'correctAnswerTe': 'నిజం',
        'verseReferenceEn': 'Acts 13:9',
        'verseReferenceTe': 'అపొస్తలుల కార్యములు 13:9',
        'explanationEn': 'Saul of Tarsus, after his conversion on the Damascus road, was also known as Paul.',
        'explanationTe': 'దమస్కు మార్గములో యేసును దర్శించిన తరువాత తార్సువాడైన సౌలు "పౌలు" అని పిలువబడెను.'
      },
      {
        'id': 'weekly_q9',
        'order': 9,
        'type': 'true_false',
        'timeLimitSeconds': 45,
        'points': 100,
        'questionEn': 'True or False: Elijah was taken to heaven in a chariot of fire.',
        'questionTe': 'నిజమా లేక తప్పా: ఏలీయా అగ్ని రథములో పరలోకమునకు కొనిపోబడెను.',
        'options': [],
        'correctAnswerEn': 'True',
        'correctAnswerTe': 'నిజం',
        'verseReferenceEn': '2 Kings 2:11',
        'verseReferenceTe': '2 రాజులు 2:11',
        'explanationEn': 'As Elijah and Elisha walked, a chariot of fire separated them, and Elijah went up in a whirlwind.',
        'explanationTe': 'ఏలీయా ఎలీషా నడుచుచుండగా అగ్నిరథమును అగ్నిగుర్రములును వారిద్దరిని వేరుపరచెను; ఏలీయా సుడిగాలిచేత ఆకాశమునకు కొనిపోబడెను.'
      },
      {
        'id': 'weekly_q10',
        'order': 10,
        'type': 'true_false',
        'timeLimitSeconds': 45,
        'points': 100,
        'questionEn': 'True or False: Jesus had twelve biological brothers.',
        'questionTe': 'నిజమా లేక తప్పా: యేసునకు పన్నెండు మంది తోడబుట్టిన సోదరులు ఉన్నారు.',
        'options': [],
        'correctAnswerEn': 'False',
        'correctAnswerTe': 'తప్పు',
        'verseReferenceEn': 'Matthew 13:55-56',
        'verseReferenceTe': 'మత్తయి 13:55-56',
        'explanationEn': 'The Gospels list four brothers of Jesus (James, Joseph, Simon, Judas) and some sisters, not twelve.',
        'explanationTe': 'యేసునకు యాకోబు, యోసేపు, సీమోను, యూదా అను నలుగురు సోదరులు మరియు సోదరీమణులు ఉన్నట్లు సువార్తలు తెలుపుచున్నవి.'
      },
      {
        'id': 'weekly_q11',
        'order': 11,
        'type': 'true_false',
        'timeLimitSeconds': 45,
        'points': 100,
        'questionEn': 'True or False: The Book of Revelation is the only prophetic book in the New Testament.',
        'questionTe': 'నిజమా లేక తప్పా: ప్రకటన గ్రంథము నూతన నిబంధనలో ఉన్న ఏకైక ప్రవచన గ్రంథము.',
        'options': [],
        'correctAnswerEn': 'True',
        'correctAnswerTe': 'నిజం',
        'verseReferenceEn': 'Revelation 1:3',
        'verseReferenceTe': 'ప్రకటన 1:3',
        'explanationEn': 'While New Testament epistles contain prophecies, Revelation is the only book classified entirely as apocalyptic prophecy.',
        'explanationTe': 'పత్రికలలో ప్రవచనాలు ఉన్నప్పటికీ, నూతన నిబంధనలో ప్రకటన గ్రంథము ఒక్కటే ప్రత్యేక ప్రవచన గ్రంథముగా వర్గీకరించబడింది.'
      },

      // 12-15: Fill in the Blanks
      {
        'id': 'weekly_q12',
        'order': 12,
        'type': 'type_answer',
        'timeLimitSeconds': 90,
        'points': 100,
        'questionEn': 'Fill in the blank: "In the beginning was the _______, and the _______ was with God."',
        'questionTe': 'ఖాళీని పూరించండి: "ఆదియందు _______ ఉండెను, _______ దేవుని వద్ద ఉండెను."',
        'options': [],
        'correctAnswerEn': 'Word',
        'correctAnswerTe': 'వాక్యము',
        'verseReferenceEn': 'John 1:1',
        'verseReferenceTe': 'యోహాను 1:1',
        'explanationEn': 'John 1:1 reveals Jesus as the pre-existent Logos (Word) who was both with God and was God.',
        'explanationTe': 'ఆదియందు వాక్యము ఉండెను, వాక్యము దేవునితో కూడ ఉండెను, వాక్యమే దేవుడై ఉండెను.'
      },
      {
        'id': 'weekly_q13',
        'order': 13,
        'type': 'type_answer',
        'timeLimitSeconds': 90,
        'points': 100,
        'questionEn': 'Fill in the blank: "I am the _______ and the truth and the life. No one comes to the Father except through me."',
        'questionTe': 'ఖాళీని పూరించండి: "నేనే _______ను, సత్యమును, జీవమును; నా ద్వారానే తప్ప ఎవడును తండ్రి యొద్దకు రాడు."',
        'options': [],
        'correctAnswerEn': 'way',
        'correctAnswerTe': 'మార్గము',
        'verseReferenceEn': 'John 14:6',
        'verseReferenceTe': 'యోహాను 14:6',
        'explanationEn': 'Jesus declares Himself as the exclusive path to reconciliation with God the Father.',
        'explanationTe': 'యేసు తాను మాత్రమే తండ్రియైన దేవుని చేరుటకు ఏకైక మార్గమని ఈ వచనములో ప్రకటించెను.'
      },
      {
        'id': 'weekly_q14',
        'order': 14,
        'type': 'type_answer',
        'timeLimitSeconds': 90,
        'points': 100,
        'questionEn': 'Fill in the blank: "For the wages of sin is _______, but the free gift of God is eternal life."',
        'questionTe': 'ఖాళీని పూరించండి: "ఏలయనగా పాపము వలన వచ్చు జీతము _______, అయితే దేవుని కృపావరము నిత్యజీవము."',
        'options': [],
        'correctAnswerEn': 'death',
        'correctAnswerTe': 'మరణము',
        'verseReferenceEn': 'Romans 6:23',
        'verseReferenceTe': 'రోమీయులకు 6:23',
        'explanationEn': 'Sin leads to eternal separation from God (death), while grace gives eternal life in Christ Jesus.',
        'explanationTe': 'పాపము యొక్క జీతము ఆత్మీయ మరణము, అయితే క్రీస్తు యేసునందు దేవుడు మనకు ఉచితముగా నిత్యజీవము ననుగ్రహించును.'
      },
      {
        'id': 'weekly_q15',
        'order': 15,
        'type': 'type_answer',
        'timeLimitSeconds': 90,
        'points': 100,
        'questionEn': 'Fill in the blank: "Trust in the Lord with all your _______, and lean not on your own understanding."',
        'questionTe': 'ఖాళీని పూరించండి: "నీ స్వబుద్ధిని ఆధారము చేసికొనక నీ పూర్ణ _______తో యెహోవా యందు నమ్మకముంచుము."',
        'options': [],
        'correctAnswerEn': 'heart',
        'correctAnswerTe': 'హృదయము',
        'verseReferenceEn': 'Proverbs 3:5',
        'verseReferenceTe': 'సామెతలు 3:5',
        'explanationEn': 'Believers are instructed to surrender their understanding and trust God fully with their heart.',
        'explanationTe': 'మానవులు తమ స్వంత జ్ఞానముపై కాక, పూర్ణ హృదయముతో దేవుని యందు నమ్మకముంచాలని జ్ఞానియైన సొలొమోను హెచ్చరించెను.'
      },

      // 16-19: Short Answer
      {
        'id': 'weekly_q16',
        'order': 16,
        'type': 'type_answer',
        'timeLimitSeconds': 90,
        'points': 100,
        'questionEn': 'What was the name of the garden where Adam and Eve lived?',
        'questionTe': 'ఆదాము అవ్వలు నివసించిన తోట పేరు ఏమిటి?',
        'options': [],
        'correctAnswerEn': 'Eden',
        'correctAnswerTe': 'ఏదెను',
        'verseReferenceEn': 'Genesis 2:15',
        'verseReferenceTe': 'ఆదికాండము 2:15',
        'explanationEn': 'The Lord God took the man and put him in the Garden of Eden to work it and take care of it.',
        'explanationTe': 'దేవుడైన యెహోవా నరుని తీసికొని ఏదెను తోటను సేద్యపరచుటకును దాని కాపాడుటకును అక్కడ ఉంచెను.'
      },
      {
        'id': 'weekly_q17',
        'order': 17,
        'type': 'type_answer',
        'timeLimitSeconds': 90,
        'points': 100,
        'questionEn': 'Who was the earthly mother of Jesus?',
        'questionTe': 'యేసు యొక్క శారీరక తల్లి ఎవరు?',
        'options': [],
        'correctAnswerEn': 'Mary',
        'correctAnswerTe': 'మరియ',
        'verseReferenceEn': 'Luke 1:30-31',
        'verseReferenceTe': 'లూకా 1:30-31',
        'explanationEn': 'The angel Gabriel visited Mary to declare that she would give birth to the Savior through the Holy Spirit.',
        'explanationTe': 'కన్యయైన మరియను దూతయైన గిబ్రియేలు దర్శించి, ఆమె పరిశుద్ధాత్మ ద్వారా గర్భము ధరించి యేసును కనునని ప్రకటించెను.'
      },
      {
        'id': 'weekly_q18',
        'order': 18,
        'type': 'type_answer',
        'timeLimitSeconds': 90,
        'points': 100,
        'questionEn': 'Which sea did the Israelites cross to escape the Egyptian army?',
        'questionTe': 'ఐగుప్తు సైన్యము నుండి తప్పించుకొనుటకు ఇశ్రాయేలీయులు దాటిన సముద్రము ఏది?',
        'options': [],
        'correctAnswerEn': 'Red Sea',
        'correctAnswerTe': 'ఎర్ర సముద్రము',
        'verseReferenceEn': 'Exodus 14:21',
        'verseReferenceTe': 'నిర్గమకాండము 14:21',
        'explanationEn': 'Moses stretched out his hand, and the Lord drove the sea back with a strong east wind, turning it into dry land.',
        'explanationTe': 'మోషే సముద్రముపై చెయ్యి చాచగా, యెహోవా తూర్పుగాలిచేత సముద్రమును పాయలుగా చేసి ఇశ్రాయేలీయులకు త్రోవ కలుగజేసెను.'
      },
      {
        'id': 'weekly_q19',
        'order': 19,
        'type': 'type_answer',
        'timeLimitSeconds': 90,
        'points': 100,
        'questionEn': 'Name the mountain where Moses received the Ten Commandments.',
        'questionTe': 'మోషే పది ఆజ్ఞలను పొందిన పర్వతము పేరు చెప్పండి.',
        'options': [],
        'correctAnswerEn': 'Sinai',
        'correctAnswerTe': 'సీనాయి',
        'verseReferenceEn': 'Exodus 19:20',
        'verseReferenceTe': 'నిర్గమకాండము 19:20',
        'explanationEn': 'The Lord descended on the top of Mount Sinai and called Moses to the top of the mountain.',
        'explanationTe': 'యెహోవా సీనాయి పర్వతము మీదికి దిగి మోషేను పర్వత శిఖరమునకు పిలువగా మోషే పైకి వెళ్లెను.'
      },

      // 20-22: Mixed Format
      {
        'id': 'weekly_q20',
        'order': 20,
        'type': 'multiple_choice',
        'timeLimitSeconds': 60,
        'points': 100,
        'questionEn': 'Which commandment is the first with a promise?',
        'questionTe': 'వాగ్దానముతో కూడిన మొదటి ఆజ్ఞ ఏది?',
        'options': [
          {'id': 'o1', 'order': 1, 'isCorrect': true, 'textEn': 'Honor your father and mother', 'textTe': 'నీ తల్లిదండ్రులను సన్మానించుము'},
          {'id': 'o2', 'order': 2, 'isCorrect': false, 'textEn': 'Do not steal', 'textTe': 'దొంగిలవద్దు'},
          {'id': 'o3', 'order': 3, 'isCorrect': false, 'textEn': 'Remember the Sabbath', 'textTe': 'విశ్రాంతి దినమును జ్ఞాపకముంచుకొనుము'},
          {'id': 'o4', 'order': 4, 'isCorrect': false, 'textEn': 'Do not commit adultery', 'textTe': 'వ్యభిచరించవద్దు'},
        ],
        'correctAnswerEn': 'Honor your father and mother',
        'correctAnswerTe': 'నీ తల్లిదండ్రులను సన్మానించుము',
        'verseReferenceEn': 'Ephesians 6:2',
        'verseReferenceTe': 'ఎఫెసీయులకు 6:2',
        'explanationEn': 'Ephesians 6:2 references the Decalogue: "Honor your father and mother," which is the first commandment with a promise: "that it may go well with you."',
        'explanationTe': 'నీకు మేలు కలుగునట్లు నీ తల్లిని తండ్రిని సన్మానించుమని పౌలు గుర్తు చేసెను, ఇది వాగ్దానముతో కూడిన మొదటి ఆజ్ఞ.'
      },
      {
        'id': 'weekly_q21',
        'order': 21,
        'type': 'multiple_choice',
        'timeLimitSeconds': 60,
        'points': 100,
        'questionEn': 'Why did Jesus wash His disciples\' feet during the Last Supper?',
        'questionTe': 'చివరి రాత్రి భోజన సమయంలో యేసు తన శిష్యుల పాదాలను ఎందుకు కడిగాడు?',
        'options': [
          {'id': 'o1', 'order': 1, 'isCorrect': true, 'textEn': 'To set an example of humility and service', 'textTe': 'వినయము మరియు సేవకు ఒక మాదిరి చూపించుటకు'},
          {'id': 'o2', 'order': 2, 'isCorrect': false, 'textEn': 'Because their feet were physically dirty', 'textTe': 'వారి పాదములు మురికిగా ఉన్నందున'},
          {'id': 'o3', 'order': 3, 'isCorrect': false, 'textEn': 'To perform a traditional Hebrew cleansing ritual', 'textTe': 'సాంప్రదాయ హెబ్రీ శుద్ధీకరణ ఆచారము చేయుటకు'},
          {'id': 'o4', 'order': 4, 'isCorrect': false, 'textEn': 'To prepare them to wear royal sandals', 'textTe': 'రాచరిక చెప్పులు ధరించుటకు వారిని సిద్ధపరచుటకు'},
        ],
        'correctAnswerEn': 'To set an example of humility and service',
        'correctAnswerTe': 'వినయము మరియు సేవకు ఒక మాదిరి చూపించుటకు',
        'verseReferenceEn': 'John 13:14-15',
        'verseReferenceTe': 'యోహాను 13:14-15',
        'explanationEn': 'Jesus washed their feet to demonstrate servant leadership, telling them: "I have given you an example, that you should do as I have done to you."',
        'explanationTe': 'ప్రభువును బోధకుడునైన యేసు శిష్యుల పాదములు కడిగి, దాసుడు తన యజమానునికంటె గొప్పవాడు కాడని వినయమును మాదిరిగా నేర్పెను.'
      },
      {
        'id': 'weekly_q22',
        'order': 22,
        'type': 'multiple_choice',
        'timeLimitSeconds': 60,
        'points': 100,
        'questionEn': 'What is the primary spiritual theme of the Parable of the Prodigal Son?',
        'questionTe': 'తప్పిపోయిన కుమారుని ఉపమానం యొక్క ముఖ్యమైన ఆత్మీయ సందేశము ఏమిటి?',
        'options': [
          {'id': 'o1', 'order': 1, 'isCorrect': true, 'textEn': 'The unconditional love and forgiveness of the Father', 'textTe': 'తండ్రి యొక్క బేషరతు ప్రేమ మరియు క్షమాగుణము'},
          {'id': 'o2', 'order': 2, 'isCorrect': false, 'textEn': 'The danger of wasting inheritance money', 'textTe': 'ఆస్తిని వృథా చేయడములోని ప్రమాదములు'},
          {'id': 'o3', 'order': 3, 'isCorrect': false, 'textEn': 'The importance of strict parenting rules', 'textTe': 'కఠినమైన పెంపక నియమాల ప్రాధాన్యత'},
          {'id': 'o4', 'order': 4, 'isCorrect': false, 'textEn': 'The agricultural details of raising swine', 'textTe': 'పందుల పెంపకములోని వ్యవసాయ వివరాలు'},
        ],
        'correctAnswerEn': 'The unconditional love and forgiveness of the Father',
        'correctAnswerTe': 'తండ్రి యొక్క బేషరతు ప్రేమ మరియు క్షమాగుణము',
        'verseReferenceEn': 'Luke 15:20-24',
        'verseReferenceTe': 'లూకా 15:20-24',
        'explanationEn': 'The parable illustrates God\'s joy and eager forgiveness when a repentant sinner returns home.',
        'explanationTe': 'పశ్చాత్తాపపడి తిరిగి వచ్చే పాపిని చేరదీసే పరలోకపు తండ్రి ప్రేమను మరియు క్షమాగుణమును యేసు ఈ ఉపమానములో వివరించెను.'
      },

      // 23-25: Skills/Application
      {
        'id': 'weekly_q23',
        'order': 23,
        'type': 'multiple_choice',
        'timeLimitSeconds': 120,
        'points': 100,
        'questionEn': 'If a brother or sister speaks angrily to you, how should you respond according to Proverbs 15:1?',
        'questionTe': 'ఎవరైనా మీతో కోపంగా మాట్లాడినప్పుడు, సామెతలు 15:1 ప్రకారం మీరు ఎలా స్పందించాలి?',
        'options': [
          {'id': 'o1', 'order': 1, 'isCorrect': true, 'textEn': 'Answer gently to turn away their wrath', 'textTe': 'వారి కోపమును చల్లార్చుటకు మృదువుగా ఉత్తరమివ్వాలి'},
          {'id': 'o2', 'order': 2, 'isCorrect': false, 'textEn': 'Shout back louder to defend your rights', 'textTe': 'మీ హక్కులను నిలబెట్టుకోవడానికి గట్టిగా అరవాలి'},
          {'id': 'o3', 'order': 3, 'isCorrect': false, 'textEn': 'Give them the silent treatment forever', 'textTe': 'వారితో మాట్లాడటం పూర్తిగా ఆపివేయాలి'},
          {'id': 'o4', 'order': 4, 'isCorrect': false, 'textEn': 'Complain to others about their bad attitude', 'textTe': 'వారి తప్పుల గురించి ఇతరులకు ఫిర్యాదు చేయాలి'},
        ],
        'correctAnswerEn': 'Answer gently to turn away their wrath',
        'correctAnswerTe': 'వారి కోపమును చల్లార్చుటకు మృదువుగా ఉత్తరమివ్వాలి',
        'verseReferenceEn': 'Proverbs 15:1',
        'verseReferenceTe': 'సామెతలు 15:1',
        'explanationEn': 'Proverbs 15:1 advises: "A soft answer turns away wrath, but a harsh word stirs up anger." Gentle responses diffuse tension.',
        'explanationTe': 'మృదువైన మాట క్రోధమును చల్లార్చును, నొచ్చుకొలిపే మాట కోపమును రేపునని ఈ వాక్యము హెచ్చరిస్తుంది.'
      },
      {
        'id': 'weekly_q24',
        'order': 24,
        'type': 'multiple_choice',
        'timeLimitSeconds': 120,
        'points': 100,
        'questionEn': 'When you feel anxious and overwhelmed by life\'s worries, what does Philippians 4:6 suggest as a direct application?',
        'questionTe': 'జీవిత చింతలతో మీరు ఆందోళనకు గురైనప్పుడు, ఫిలిప్పీయులకు 4:6 సూచించే ఆచరణాత్మక పరిష్కారం ఏది?',
        'options': [
          {'id': 'o1', 'order': 1, 'isCorrect': true, 'textEn': 'Pray about everything with thanksgiving, presenting requests to God', 'textTe': 'కృతజ్ఞతాపూర్వకముగా ప్రార్థన విజ్ఞాపనల ద్వారా మీ విన్నపాలు దేవునికి తెలియజేయాలి'},
          {'id': 'o2', 'order': 2, 'isCorrect': false, 'textEn': 'Worry in secret until a solution naturally appears', 'textTe': 'సమస్య పరిష్కారం అయ్యే వరకు ఒంటరిగా చింతించాలి'},
          {'id': 'o3', 'order': 3, 'isCorrect': false, 'textEn': 'Distract yourself with work or entertainment to ignore the anxiety', 'textTe': 'ఆందోళనను మరిచిపోవడానికి వేరే పనులలో నిమగ్నం కావాలి'},
          {'id': 'o4', 'order': 4, 'isCorrect': false, 'textEn': 'Seek financial or worldly security to resolve the fear', 'textTe': 'భయము పోగొట్టుకోవడానికి లోకసంబంధమైన సహాయము వెతకాలి'},
        ],
        'correctAnswerEn': 'Pray about everything with thanksgiving, presenting requests to God',
        'correctAnswerTe': 'కృతజ్ఞతాపూర్వకముగా ప్రార్థన విజ్ఞాపనల ద్వారా మీ విన్నపాలు దేవునికి తెలియజేయాలి',
        'verseReferenceEn': 'Philippians 4:6',
        'verseReferenceTe': 'ఫిలిప్పీయులకు 4:6',
        'explanationEn': 'Philippians 4:6 says: "Do not be anxious about anything, but in everything by prayer and supplication with thanksgiving let your requests be made known to God."',
        'explanationTe': 'దేనిని గూర్చియు చింతపడకుడి గాని ప్రతి విషయములోను కృతజ్ఞతాపూర్వకముగా ప్రార్థన ప్రార్థనల ద్వారా మీ విన్నపములు దేవునికి తెలియజేయుడి.'
      },
      {
        'id': 'weekly_q25',
        'order': 25,
        'type': 'multiple_choice',
        'timeLimitSeconds': 120,
        'points': 100,
        'questionEn': 'According to James 1:19, how should a Christian behave in conversation and response to conflict?',
        'questionTe': 'యాకోబు 1:19 ప్రకారం, వివాదాలు లేదా సంభాషణల సమయంలో ఒక క్రైస్తవుడు ఎలా ప్రవర్తించాలి?',
        'options': [
          {'id': 'o1', 'order': 1, 'isCorrect': true, 'textEn': 'Be quick to listen, slow to speak, and slow to become angry', 'textTe': 'వినడానికి వేగిరపడేవాడుగాను, మాట్లాడడానికి నిదానించేవాడుగాను, కోపించడానికి నిదానించేవాడుగాను ఉండాలి'},
          {'id': 'o2', 'order': 2, 'isCorrect': false, 'textEn': 'Be quick to defend your point, speaking fast to win the argument', 'textTe': 'వాదన గెలవడానికి వేగంగా మాట్లాడి మీ అభిప్రాయాన్ని బలంగా చెప్పాలి'},
          {'id': 'o3', 'order': 3, 'isCorrect': false, 'textEn': 'Be quick to judge others, slow to listen to their context', 'textTe': 'ఇతరులను త్వరగా తీర్పు తీర్చి, వారి మాట వినకుండా ఉండాలి'},
          {'id': 'o4', 'order': 4, 'isCorrect': false, 'textEn': 'Be quick to express anger to make others respect you', 'textTe': 'ఇతరులు మిమ్మల్ని గౌరవించేలా త్వరగా కోపము చూపించాలి'},
        ],
        'correctAnswerEn': 'Be quick to listen, slow to speak, and slow to become angry',
        'correctAnswerTe': 'వినడానికి వేగిరపడేవాడుగాను, మాట్లాడడానికి నిదానించేవాడుగాను, కోపించడానికి నిదానించేవాడుగాను ఉండాలి',
        'verseReferenceEn': 'James 1:19',
        'verseReferenceTe': 'యాకోబు 1:19',
        'explanationEn': 'James exhorts: "Let every person be quick to hear, slow to speak, slow to anger," which promotes godly relationships.',
        'explanationTe': 'ప్రతి మనుష్యుడు వినుటకు వేగిరపడువాడును, మాటలాడుటకు నిదానించువాడును, కోపించుటకు నిదానించువాడునై యుండవలెనని యాకోబు బోధించెను.'
      }
    ];
  }
}
